// <auto-generated />
using System;
using Concentrix.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Concentrix.Migrations
{
    [DbContext(typeof(PedidosDbContext))]
    [Migration("20250122132946_Concentrix")]
    partial class Concentrix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Concentrix.Models.Itens", b =>
                {
                    b.Property<int>("idItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Pedidosid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nomePedido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<double>("valorUnitario")
                        .HasColumnType("REAL");

                    b.HasKey("idItem");

                    b.HasIndex("Pedidosid");

                    b.ToTable("gerarItens");
                });

            modelBuilder.Entity("Concentrix.Models.Pedidos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dataPedido")
                        .HasColumnType("TEXT");

                    b.Property<string>("nomeCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("valorTotalPedido")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("gerarPedidos");
                });

            modelBuilder.Entity("Concentrix.Models.Itens", b =>
                {
                    b.HasOne("Concentrix.Models.Pedidos", null)
                        .WithMany("ItensPedidos")
                        .HasForeignKey("Pedidosid");
                });

            modelBuilder.Entity("Concentrix.Models.Pedidos", b =>
                {
                    b.Navigation("ItensPedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
